#!/bin/bash 
set -e   # fail on error

###
# #%L
# **********************************************************************
# PROJECT       :  rpi-scripts
# FILENAME      :  rpi-wifi-config-push
# **********************************************************************
# 
# Copyright (C) 2015 Robert Savage
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
###

echo
echo "******************************************************"
echo "******************************************************"
echo "**                                                  **"
echo "**  THIS IS A CUSTOM SHELL SCRIPT FOR DEPLOYING     **"
echo "**  A LOCAL COPY OF THE 'wpa_supplicant.conf'       **"
echo "**  WIFI CONFIGURATION FILE TO THE RASPBERRY PI.    **"
echo "**                                                  **"
echo "******************************************************"
echo "******************************************************"
echo

# set Raspberry Pi host address
USERNAME=pi
HOST=$1
PORT=$2

# validate that a host argument was provided
if [ -z $HOST ]; then 
	echo "-------------------------------"
	echo " MISSING RASPBERRY PI HOST ARG"
	echo "-------------------------------"
	echo "SYNTAX: ./rpi-auth {pi-host-address}"
	echo
	exit
fi

# allow custom port argument
if [ -z $PORT ] 
  then 
	PORT=22
fi

# display host information to user
echo "------------------------------"
echo " TARGET RASPBERRY PI HOST:    "
echo "------------------------------"
echo " ADDRESS : $HOST"
echo " PORT    : $PORT"

# copy the local 'wpa_supplicant.conf file to the Raspberry Pi
echo
echo "------------------------------"
echo " COPY WIFI CONFIG FILE TO PI   "
echo "------------------------------"
echo "(Note: You may need to enter the default Raspberry Pi password below if prompted)"
set -x
scp -P $PORT wpa_supplicant.conf $USERNAME@$HOST:wpa_supplicant.conf
set +x

# SSH to the Raspberry Pi to complete moving the wifi config file to the correct location
echo
echo "------------------------------"
echo " COMPLETE WIFI CONFIG         "
echo "------------------------------"
echo "(Note: You may need to enter the default Raspberry Pi password below if prompted)"
set -x
ssh -p $PORT $USERNAME@$HOST bash -c "'
sudo mv ~/wpa_supplicant.conf /etc/wpa_supplicant/wpa_supplicant.conf
'"
set +x

# ... all done ...
echo
echo "------------------------------"
echo " FINISHED "
echo "------------------------------"
echo

